package lessons.lesson18.homeworks

fun main() {
    println("=== DEMO: Fridge ===")
    val fridge = Fridge()
    fridge.powerOn()
    fridge.open()
    fridge.setTemperature(-12)
    fridge.programAction("Супер-заморозка")
    fridge.execute()
    fridge.emitLight()
    fridge.close()
    fridge.clean()
    fridge.powerOff()

    println("\n=== DEMO: WashingMachine ===")
    val wm = WashingMachine()
    wm.connectToWaterSupply()
    wm.connectToDrain()
    wm.powerOn()
    wm.setTemperature(60)
    wm.setTimer(90)
    wm.programAction("Хлопок интенсивный")
    wm.getWater(20)
    wm.execute()
    wm.drain()
    wm.powerOff()

    println("\n=== DEMO: Kettle ===")
    val kettle = Kettle()
    kettle.fillWater(800)
    kettle.powerOn()
    kettle.setTemperature(90)
    kettle.programAction("Поддержание температуры")
    kettle.execute()
    kettle.getWater(300)
    kettle.powerOff()

    println("\n=== DEMO: Oven ===")
    val oven = Oven()
    oven.powerOn()
    oven.open()
    oven.setTemperature(200)
    oven.programAction("Выпечка пирога 45 мин")
    oven.close()
    oven.execute()
    oven.clean()
    oven.powerOff()
}
